name: "My first github action"

# 특정 job은 push에만 돌고 pull에는 돌지 말라고 할 수 있다.
# 하지만 멘토님 개인적으로 추천하지 않음.
on: ["push", "pull_request"]

jobs:
  first-job:
    name: "first job"

    # 세 os에서 동시에 돌아간다.
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
        nodejs: ["14.x", "16.x"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs }}

      - name: output value from ${{ matrix.os }}
        id: first
        shell: bash
        run: |
          echo "OS: ${{ matrix.os }}"
          echo "node.js: ${{ matrix.nodejs }}"
